#env = LANG,en_US.UTF-8
#env = LC_TIME,en_US.UTF-8

####################
### АВТОЗАПУСК ####
##################

exec-once = hyprlauncher -d
exec-once = [workspace 3 silent] Telegram -autostart
# exec-once = [workspace 3 silent] bash ~/.config/xray/v2ray-gtk-client-zaraza/start.sh
exec-once = ~/.config/xray/xray.sh

#####################
### Буфер обмена ### 
###################

### Требуется wl-clipboard
exec-once = wl-clipboard-history -t
exec-once = wl-paste --watch cliphist store
### буфер обмена при закрытии приложений ### Требуется wl-clip-persist  
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


#########################
### Системные службы ### 
#######################
exec-once = bash -c '[ -f ~/.config/background ] || bash ~/.config/hypr/set-background-rofi.sh'
exec-once = awww-daemon
exec-once = eww daemon 
exec-once = eww open clock-window
exec-once = eww open activate-linux
exec-once = swaync
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = ~/.config/hypr/wifi_monitor.sh
