#######################
### ПРИВЯЗКИ КЛАВИШ ###
#######################

# https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER         # Win как основной модификатор

# Основные привязки, подробности: https://wiki.hypr.land/Configuring/Binds/
bind = $mainMod, D, exec, discord
bind = $mainMod, Q, exec, $terminal_2     # Win + Q → Терминал
bind = $mainMod, A, exec, $terminal_2 --config-file .config/alacritty/plus_zellij.toml
bind = $mainMod SHIFT, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit  # Win + M → Выход
bind = $mainMod, E, exec, $fileManager  # Win + E → Файловый менеджер
bind = $mainMod, R, exec, ~/.config/hypr/hyprland_configs/scripts/wofi_toggle.sh         # Win + R → Меню
bind = $mainMod, L, exec, $hyprlock     # Win + L → Блокировка экрана
bind = $mainMod, F, exec, $browser      # ← ДОБАВЛЕНО: Win + F → Firefox
bind = $mainMod, T, exec, $Telegram     # Telegram
bind = $mainMod, X, exec, xed
bind = $mainMod, S, exec, wlogout
bind = $mainMod, H, exec, ~/.config/hypr/hyprland_configs/scripts/cliphist_toggle.sh 
bind = $mainMod, N, exec, swaync-client -t

####### СКРИНШОТЫ ЭКРАНА
bind = SHIFT, Print, exec, bash -c 'mkdir -p ~/Screenshots && grim -g "$(slurp -d)" - | tee ~/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy'
bind = ,Print, exec, bash -c 'mkdir -p ~/Screenshots && grim ~/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png && wl-copy < ~/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png'

bind = $mainMod, W, exec, bash -c ~/.config/hypr/set-background-rofi.sh



# Мультимедиа-клавиши ноутбука (громкость, яркость)
    bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
    bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    bindel = , XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
    bindel = , XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Музыка (требует playerctl)
    bindl = , XF86AudioNext, exec, playerctl next
    bindl = , XF86AudioPause, exec, playerctl play-pause
    bindl = , XF86AudioPlay, exec, playerctl play-pause
    bindl = , XF86AudioPrev, exec, playerctl previous

