
#######################################################
# ресайз окон если используешь scrolling раскладку####
#####################################################

bind = $mainMod CTRL, H,  layoutmsg, colresize -0.05
bind = $mainMod CTRL, L, layoutmsg, colresize +0.05
bind = $mainMod CTRL, K,    layoutmsg, colresize +0.05
bind = $mainMod CTRL, J,  layoutmsg, colresize -0.05

bind = $mainMod CTRL, H, layoutmsg, colresize -0.05
bind = $mainMod CTRL, L, layoutmsg, colresize +0.05
bind = $mainMod CTRL, K, layoutmsg, colresize +0.05
bind = $mainMod CTRL, J, layoutmsg, colresize -0.05


bind = $mainMod, V, togglefloating,     # Win + V → Плавающее окно
bind = $mainMod, P, pseudo,             # Win + P → Псевдо-тайлинг (dwindle)
bind = $mainMod, B, exec, hyprctl dispatch fullscreen 1

