##########################################
### ПЕРЕМЕННЫЕ С ОСНОВНЫМИ ПРОГРАММАМИ ###
##########################################

$terminal = kitty
$terminal_2 = alacritty
$fileManager = nemo
$menu = wofi --show drun
$hyprlock = hyprlock
$browser = firefox
$Telegram = Telegram
