exec-once = hyprpm reload
plugin {
    hyprbars { #hyprpm enable/disable hyprbars  
        bar_height = 24
        bar_color = rgb(242424)
        bar_blur = true

        bar_title_enabled = true
        bar_text_size = 8
        bar_text_font = Monospace Bold

        bar_text_align = center
        bar_buttons_alignment = left

        bar_padding = 9
        bar_button_padding = 7

        col.text = $itc
        hyprbars-button = rgb(C94D54), 12, , hyprctl dispatch killactive
        hyprbars-button = rgb(D0AB3B), 12, , ~/.config/hypr/hyprland_configs/toggle-floating.sh
        hyprbars-button = rgb(36C94A), 12, , hyprctl dispatch fullscrean 1
    }

    hyprexpo {
        columns = 4
            gap_size = 1
            bg_col = $itc
            workspace_method = first 1 #center current # [center/first] [workspace] e.g. first 1 or center m+1

            gesture_distance = 200 # how far is the "max" for the gesture
    }
    bind = SUPER, E, hyprexpo:expo, toggle
}
