##############################
### ОКНА И РАБОЧИЕ СТОЛЫ ###
##############################

# Правила окон: https://wiki.hypr.land/Configuring/Window-Rules/
# Правила столов: https://wiki.hypr.land/Configuring/Workspace-Rules/

# Полезные правила окон

windowrule {
# Игнорировать запросы на максимизацию от всех приложений
    name = suppress-maximize-events
        match:class = .*
        suppress_event = maximize
}

windowrule {
# Исправление проблем с перетаскиванием в XWayland
    name = fix-xwayland-drags
        match:class = ^$
        match:title = ^$
        match:xwayland = true
        match:float = true
        match:fullscreen = false
        match:pin = false
        no_focus = true
}

# Правило для hyprland-run (меню запуска)
windowrule {
    name = move-hyprland-run
        match:class = hyprland-run
        move = 20 monitor_h-120
        float = yes
}

# Правило для окна "Свойства файла" в Nemo (центрированное)
windowrule {
    name = move-nemo-properties
        match:class = nemo
        match:title = .*(Свойства|Properties).*
        float = yes
        center = yes
}

# Правило для окна "Извлечь" в Nemo (центрированное)
windowrule {
    name = Извлечь
        match:class = org.gnome.FileRoller
        match:title = .*.*
        float = yes
        center = yes
        max_size = 400 100
}

windowrule {
    name = no_opacity
        match:class = gimp|firefox|org.telegram.desktop|gjs|viewnior|org.gnome.Evince|discord
        opacity = 1.0 override 1.0 override
}


windowrule {
    name = Wallpapers
        match:title = .*(Wallpapers).*
        match:class = xdg-desktop-portal-gtk
        float = yes
        center = yes
        max_size = 900 500
}

windowrule {
    name = float_pleas
        match:title = float_pleas
        float = yes
        center = yes
}

layerrule {
    name = notification center       # Имя правила (для удобства)
    match:namespace = swaync-control-center
    animation = slide right            # Анимация: выезжает сверху
}

layerrule {
    name = rofi_wallpaper_select       # Имя правила (для удобства)
    match:namespace = rofi
    animation = slide bottom            # Анимация: выезжает сверху
    blur = true
}
