# label {
#     monitor =
#     text = ---- 󰣇 ----
#     color = $icon_text_color
#     font_size = 24
#     font_family = Adwaita Mono
#     position = 0, -271
#     halign = center
#     valign = center
# }

label {
    monitor =
        text = 󰣇                            .
        color = $background_standart_color
        font_size = 44
        font_family = $стандартный_шрифт
        position = 300, 100
        halign = right
        valign = bottom
}
