shape {  # Фон плашки (круг)
    monitor =
        size = 40, 40  # Ширина плашки, высота
        color = $background_standart_color # Полупрозрачный
        rounding = $кругление_плашек
        position = 130, $shifting_downwards
        halign = center
        valign = center
        onclick = systemctl suspend  # Команда при клике
}

label {
    monitor =
        text = 󰤄
        color = $itc
        font_size = 24
        font_family = Adwaita Mono
        position = 128, $shifting_downwards
        halign = center
        valign = center
        onclick = systemctl suspend  # Команда при клике
}
