######## АВАТАР ########
USER AVATAR
image {
    monitor =
        path = $HOME/.face
        size = 170
        border_color = rgba(0, 0, 0, 1.0) #    $accent
        border_size = 5  # Толщина рамки
        position = 0, 100
        halign = center
        valign = center
}
