general {
    # Команда блокировки (не плодим процессы)
    lock_cmd = pidof hyprlock || hyprlock

    # Заблокировать перед сном
    before_sleep_cmd = loginctl lock-session

    # Включить экран после пробуждения (чтобы не жать два раза)
    after_sleep_cmd = hyprctl dispatch dpms on

    # 3 — система ждёт, пока сессия реально заблокируется
    inhibit_sleep = 3
}

# Через 5 минут бездействия — блокировка
listener {
    timeout = 300                       # время в секундах
    on-timeout = loginctl lock-session  # тут дергается lock_cmd -> hyprlock
}

# Через 5.5 минут — выключить монитор
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Через 30 минут — усыпить систему
listener {
    timeout = 620
    on-timeout = systemctl suspend
}

