$background_standart_color = rgba(0, 0, 0, 1.0) # цвет плашек (0, 0, 0, 1.0)
$shifting_downwards = -340 # смещение кнопок по вертикали от центра
$кругление_плашек = 20
$стандартный_шрифт = SF Pro Display Bold 

    source = ~/.config/hypr/colors/color.conf
    source = ~/.config/hypr/hyprlock_configs/sleep_button.conf # кнопка спящего режима
    source = ~/.config/hypr/hyprlock_configs/input-field.conf  # поле воода пароля
    source = ~/.config/hypr/hyprlock_configs/clock_widget.conf  # виджет часов
    # source = ~/.config/hypr/hyprlock_configs/user_avatar.conf  # аватар пользователя



######## ГЛАВНЫЕ НАСТРОЙКИ ПОВЕДЕНИЯ ########

    general {
        disable_loading_bar = true
        hide_cursor = false
        grace = 3
        no_fade_in = true #false
    }

######## ОБОИ ########

background {
    monitor =
        path = ~/.config/background
        blur_passes = 0 #число проходов блюра 
        blur_size = 15
        noise = 0.0117
        contrast = 1.3000
        brightness = 0.4000
        vibrancy = 0.2100
        vibrancy_darkness = 0.0
}




