# shape {  # Фон плашки (прямоугольник)
#     monitor =
#         size = 100, 40  # Ширина плашки, высота
#         color = $background_standart_color  # Полупрозрачный
#         rounding = $кругление_плашек
#         position = -110, $shifting_downwards
#         blur_passes = 10 #число проходов блюра 
#         blur_size = 4
#         noise = 0.0117
#         halign = center
#         valign = center
# }
label {  # Виджет часов
    monitor =
        text = $TIME
        color = $bg1
        font_size = 76
        font_family = $стандартный_шрифт
        position = 2, -52
        halign = center
        valign = top
}
label {  # Виджет часов
    monitor =
        text = $TIME
        color = $itc2
        font_size = 76
        font_family = $стандартный_шрифт
        position = 0, -50
        halign = center
        valign = top
}
