######## ВВОД ########
shape { 
    monitor =
        size = 160, 40  # Ширина плашки, высота
        color = $bg2 $background_standart_color # Полупрозрачный
        rounding = 20
        position = 0, 20
        halign = center
        valign = bottom
}

input-field {
    fail_text = error 
        fail_timeout = 100  # опционально, быстрее исчезновение
        monitor =
        size = 114, 32
        outline_thickness = 0
        outer_color = $itc
        font_color = $itc
        inner_color = $bg2
        fade_on_empty = false
        placeholder_text = Password
        font_size = 21
        # font_family = $стандартный_шрифт
        hide_input = false
        check_color = rgb(b30000)
        fail_color = rgb(b30000)    # macOS red
        dots_center = true
        dots_spacing = 0.4

        position = 19, 24
        halign = center
        valign = bottom
        rounding = 25
}
shape {  # Фон плашки (круг)
    monitor =
        size = 32, 32  # 40*0.8, 40*0.8
        color = $itc2
        rounding = 20    # 25*0.8
        onclick = systemctl suspend  # Команда при клике
        position = -60, 24
        halign = center
        valign = bottom
}

image {
    monitor =
        path = $HOME/.config/hypr/hyprlock_configs/1366x768/icons/logout.png
        size = 24  # 30*0.8
        border_color = rgba(0, 0, 0, 1.0) #    $accent
        border_size = 0
        onclick = systemctl suspend  # Команда при клике
        position = -60, 28
        halign = center
        valign = bottom
}
