######## ВВОД ########
shape { 
    monitor =
        size = 160, 40  # Ширина плашки, высота
        color = $bg2 $background_standart_color # Полупрозрачный
        rounding = 20
        position = 0, 20
        halign = center
        valign = bottom
}
image {
    monitor =
        path = $HOME/.face
        size = 32
        border_color = rgba(0, 0, 0, 1.0) #    $accent
        border_size = 0
        position = -60, 24
        halign = center
        valign = bottom
        onclick = hyprctl dispatch exit
}

input-field {
    fail_text = error 
        fail_timeout = 100  # опционально, быстрее исчезновение
        monitor =
        size = 120, 40
        outline_thickness = 0
        outer_color = $itc
        font_color = $itc
        inner_color = rgba(00000000)
        fade_on_empty = false
        placeholder_text = Password
        font_size = 21
        # font_family = $стандартный_шрифт
        hide_input = false
        check_color = rgb(b30000)
        fail_color = rgb(b30000)    # macOS red
        dots_center = true
        dots_spacing = 0.4

        position = 16, 20
        halign = center
        valign = bottom
        rounding = 25
}

