shape {  # Фон плашки (круг)
    monitor =
        size = 140, 40  # 175*0.8, 50*0.8
        color = $bg2 $background_standart_color # Полупрозрачный
        rounding = 20    # 25*0.8
        position = 144, 16  # 180*0.8, 20*0.8
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}

shape {  # Фон плашки (круг)
    monitor =
        size = 32, 32  # 40*0.8, 40*0.8
        color = $itc
        rounding = 20    # 25*0.8
        position = 148, 20  # 185*0.8, 25*0.8
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}

label {
    monitor =
        text = Shutdown
        color = $itc2
        font_size = 13  # 16*0.8
        font_family = Adwaita Mono
        position = 185.6, 25.6  # 232*0.8, 32*0.8
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}

image {
    monitor =
        path = $HOME/.config/hypr/hyprlock_configs/1366x768/icons/shutdown.png
        size = 24  # 30*0.8
        border_color = rgba(0, 0, 0, 1.0) #    $accent
        border_size = 0
        position = 152, 24  # 190*0.8, 30*0.8
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}
