shape {  # Фон плашки (круг)
    monitor =
        size = 112, 40  # 140*0.8, 50*0.8
        color = $bg2 $background_standart_color # Полупрозрачный
        rounding = 20    # 25*0.8
        position = 16, 16  # 20*0.8, 20*0.8
        halign = left
        valign = bottom
        onclick = systemctl suspend  # Команда при клике
}

shape {  # Фон плашки (круг)
    monitor =
        size = 32, 32  # 40*0.8, 40*0.8
        color = $itc2
        rounding = 20    # 25*0.8
        position = 20, 20  # 25*0.8, 25*0.8
        halign = left
        valign = bottom
        onclick = systemctl suspend  # Команда при клике
}

label {
    monitor =
        text = Sleep
        color = $itc2
        font_size = 13  # 16*0.8
        font_family = Adwaita Mono
        position = 57.6, 25.6  # 72*0.8, 32*0.8
        halign = left
        valign = bottom
        onclick = systemctl suspend  # Команда при клике
}

image {
    monitor =
        path = $HOME/.config/hypr/hyprlock_configs/1366x768/icons/sleep.png
        size = 24  # 30*0.8
        border_color = rgba(0, 0, 0, 1.0) #    $accent
        border_size = 0
        position = 24, 24  # 30*0.8, 30*0.8
        halign = left
        valign = bottom
        onclick = systemctl suspend  # Команда при клике
}
