
shape {  # Фон плашки (круг)
    monitor =
        size = 175, 50  # Ширина плашки, высота
        color = $background_standart_color # Полупрозрачный
        rounding = 25
        position = 180, 20
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}

shape {  # Фон плашки (круг)
    monitor =
        size = 40, 40  # Ширина плашки, высота
        color = $itc
        rounding = 25
        position = 185, 25
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}
label {
    monitor =
        text = Shutdown
        color = $itc2
        font_size = 16
        font_family = Adwaita Mono
        position = 232, 32
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}
image {
    monitor =
        path = $HOME/.config/hypr/hyprlock_configs/1920x1080/icons/shutdown.png
        size = 30
        border_color = rgba(0, 0, 0, 1.0) #    $accent
        border_size = 0
        position = 190, 30
        halign = left
        valign = bottom
        onclick = systemctl poweroff  # Команда при клике
}
